# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ded2d1bdfadfa5bb14b3f00905cb1a1e423b54e14497f2e23fcabd1d526cc77d524687da15a9a013fca9ff7fad194416e12e442984c0ee56ae9af389ab939b3

test:
  secret_key_base: d3187b5acabbbc32c8963848af720b33fe2e16f3e9e8332679eb31cdd3c25389916cf32b0dce45011ed2ebca2ea29f81d0cde855a5fa32226eea50cadf080a97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
